### ISSUE TITLE
Handshake failed: tlsv1 alert internal error

### ISSUE THREAD

**Issue by drkvogel** [alexandruc/SimpleHttpsClient#3]
Thanks for this example, but I can't get it to work. I get `Handshake failed: tlsv1 alert internal error`:

```
$ make SimpleHttpsClient; ./SimpleHttpsClient.exe httpbin.org /ip
g++ -std=c++11 -Wall  SimpleHttpsClient.cpp -lpthread -lssl -lcrypto -Wl,-rpath,/home/smsdb/local/lib -I ~/local/include ~/local/lib/libboost_system.so -o SimpleHttpsClient.exe
Resolve OK
Connect OK
Handshake failed: tlsv1 alert internal error
```

If I use `boost::asio::ssl::context ctx(boost::asio::ssl::context::sslv2);` instead lf `sslv23`, I get `Handshake failed: End of file` instead.

**Comment by alexandruc** [comment]
I think it has to do with the openssl version you have on your machine. Make sure you have openssl compiled with TLS 1.2+ available and build boost with it.
Also, you can make a simple test using the curl verbose command line, in order to see what SSL protocol you get resolved from the server you are connecting to.

**Comment by drkvogel** [comment]
I have openssl and libssl-dev version 1.0.2d-0ubuntu1.5:

```
    $ sudo apt-cache policy openssl libssl-dev 
    openssl:
      Installed: 1.0.2d-0ubuntu1.5
      ...
    libssl-dev:
      Installed: 1.0.2d-0ubuntu1.5
```

and curl to one of the URLs that failed, works:

```
    $ curl -v https://httpbin.org
    * Rebuilt URL to: https://httpbin.org/
    *   Trying 107.20.178.140...
    * Connected to httpbin.org (107.20.178.140) port 443 (#0)
    * ALPN, offering http/1.1
    * SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
    *    server certificate verification OK
    ...
    * ALPN, server accepted to use http/1.1
    > GET / HTTP/1.1
    > Host: httpbin.org
    > User-Agent: curl/7.43.0
    > Accept: */*
    < HTTP/1.1 200 OK
    ...
```

**Comment by drkvogel** [comment]
It looks like there might be a bug in that (Ubuntu) version of openssl: <https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1475228>.

but... I only see the error when trying to connect to httpbin.org - which I was using for testing. The actual URL I want to connect to, I can. So it seems to be a combination of Boost, openssl 1.0.2d-0ubuntu1.5, and httpbin.org! Or perhaps Boost and httpbin.org, as I've seen this "internal error" on CentOS as well.

**Comment by alexandruc** [comment]
You have to build boost with the proper openssl version and TLS version support.
It seems to me that you are using the boost and openssl versions bundled with your version of ubuntu.
You should build them manually in order to control better your dependencies.
I am closing this issue since it is not related to the project.

**Comment by josthelvish** [comment]
First, I would like to thank you @alexandruc for the sample project, it helped me a lot.
I ran into the same error and like to share what I found:

Some hosts don't agree with the handshake due to SNI:

https://stackoverflow.com/questions/5113333/how-to-implement-server-name-indication-sni
https://stackoverflow.com/questions/30538542/tlsv1-alert-internal-error-during-handshake
https://stackoverflow.com/questions/43845416/ssl3-read-bytestlsv1-alert-internal-error-secure-sockets-openssl-c-gettin

What I was trying was https://www.httpbin.org, you can try it.

I solved it adding the following piece of code to the handle_resolve:

```c
if (!SSL_set_tlsext_host_name(socket_.native_handle(), <hostname>)) {
       boost::system::error_code ec{static_cast<int>(::ERR_get_error()),
                    boost::asio::error::get_ssl_category()};
      std::cerr << ec.message() << "\n";
      return;
}
```

Once again, thanks ;)

**Comment by asn10038** [comment]
hey big thanks @josthelvish and @alexandruc
